import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#eef9fb' },
  topHeader: { backgroundColor: '#2c4760', flexDirection: 'row', alignItems: 'center', padding: 15 },
  headerLogo: { width: 30, height: 30, marginRight: 10 },
  headerTitle: { color: '#fff', fontSize: 22, fontWeight: 'bold' },
  welcomeBar: { backgroundColor: '#5ba1a6', flexDirection: 'row', justifyContent: 'space-between', padding: 15, alignItems: 'center' },
  welcomeText: { color: '#fff', fontSize: 20, fontWeight: '500' },
  bellIcon: { width: 20, height: 20, tintColor: '#fff' },
  content: { flex: 1, padding: 15 },
  filterRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  userCount: { borderBottomWidth: 2, borderBottomColor: '#5ba1a6', paddingBottom: 5 },
  userCountText: { fontSize: 16, color: '#2c4760', fontWeight: 'bold' },
  countBadge: { backgroundColor: '#5ba1a6', color: '#fff', paddingHorizontal: 6, borderRadius: 10, overflow: 'hidden' },
  addUserBtn: { backgroundColor: '#7ba1b3', paddingVertical: 8, paddingHorizontal: 15, borderRadius: 8 },
  addUserBtnText: { color: '#fff', fontWeight: 'bold' },
  searchContainer: { backgroundColor: '#fff', borderRadius: 10, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, height: 45, borderWidth: 1, borderColor: '#ddd', marginBottom: 10 },
  searchInput: { flex: 1 },
  roleFilter: { backgroundColor: '#fff', width: 120, height: 35, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 10, marginBottom: 15 },
  userCard: { backgroundColor: '#fff', borderRadius: 15, padding: 15, marginBottom: 15, borderWidth: 1, borderColor: '#dcf1f4' },
  cardMain: { flexDirection: 'row' },
  avatar: { width: 60, height: 60, borderRadius: 30, backgroundColor: '#eee' },
  userInfo: { marginLeft: 15, flex: 1 },
  userName: { fontSize: 18, fontWeight: 'bold', color: '#2c4760' },
  userDetail: { fontSize: 12, color: '#666', marginVertical: 4 },
  roleContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 5 },
  roleLabel: { backgroundColor: '#dcf1f4', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 5, marginRight: 5 },
  roleLabelText: { fontSize: 10, color: '#2c4760', fontWeight: 'bold' },
  roleBadge: { backgroundColor: '#749494', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  roleBadgeText: { fontSize: 11, color: '#fff' },
  actionRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 15, borderTopWidth: 1, borderTopColor: '#eee', paddingTop: 10 },
  miniBtn: { backgroundColor: '#f8fbfc', borderWidth: 1, borderColor: '#ddd', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  miniBtnText: { fontSize: 13, color: '#555' },
  rightActions: { flexDirection: 'row' },
  actionBtn: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8, marginLeft: 8, flexDirection: 'row', alignItems: 'center' },
  actionBtnText: { color: '#fff', fontSize: 13, fontWeight: 'bold' },
  bottomNav: { flexDirection: 'row', height: 70, borderTopWidth: 1, borderTopColor: '#ddd', backgroundColor: '#fff', justifyContent: 'space-around', alignItems: 'center' },
  navItem: { alignItems: 'center' },
  navIcon: { width: 24, height: 24 },
  navLabel: { fontSize: 12, color: '#666', marginTop: 4 }
});